apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-credentials
type: Opaque
data:
  docker_hub_username: {{ .Values.global.containers.docker_hub_username | b64enc | quote }}
  docker_hub_password: {{ .Values.global.containers.docker_hub_password | b64enc | quote }}
