apiVersion: v1
kind: ServiceAccount
metadata:
  name: cincodebio-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cincodebio-role
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "get"]
  - apiGroups: [""]
    resources: ["pods", "services", "persistentvolumeclaims", "namespaces"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs", "jobs/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cincodebio-rolebinding
subjects:
  - kind: ServiceAccount
    name: cincodebio-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: cincodebio-role
  apiGroup: rbac.authorization.k8s.io
